apiVersion: v2
name: jx
description: Jenkins X next gen cloud CI / CD platform for Kubernetes
home: https://jenkins-x.io/
version: 0.0.1
appVersion: 3.0.0
icon: https://jenkins-x.github.io/jenkins-x-website/img/profile.png
sources:
- https://github.com/jenkins-x/jx
maintainers:
- name: Jenkins X Team
  email: jenkins-x@googlegroups.com