apiVersion: v1
appVersion: 2.1.97
description: Jenkins X next gen cloud CI / CD platform for Kubernetes
home: https://jenkins-x.io/
icon: https://jenkins-x.github.io/jenkins-x-website/img/profile.png
maintainers:
- email: jenkins-x@googlegroups.com
  name: Jenkins X Team
name: jx
sources:
- https://github.com/jenkins-x/jx
version: 2.1.97
