{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jx.name" . }}
  labels:
    app: {{ template "jx.name" . }}
    chart: {{ template "jx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.serviceAnnotations }}
  annotations:
{{ toYaml .Values.service.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "jx.name" . }}
    release: {{ .Release.Name }}
{{- end }}